version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pocket_gera:/var/lib/postgresql/data

volumes:
  pocket_gera: